parameters: []
post:
  summary: Vault Configuration Report
  parameters:
  - name: Authorization
    in: header
    required: false
    example: '{{sessionId}}'
    schema:
      type: string
  - name: Content-Type
    in: header
    required: false
    example: application/x-www-form-urlencoded
    schema:
      type: string
  - name: X-VaultAPI-ClientID
    in: header
    required: false
    description: Include a Client ID to identify this request. This ID appears
      in the API Usage Logs, which is avaiable to download from Admin > Logs >
      API Usage Logs or through the Vault REST API with the Download Daily API
      Usage request. If omitted, the value will appear as `unknown` in the API
      Usage Log.
    example: '{{clientId}}'
    schema:
      type: string
  - name: version
    in: path
    required: true
    description: The version parameter.
    schema:
      type: string
  responses:
    '200':
      description: Success
  description: No description available.
  operationId: api_version_objects_vault_actions_configreport_cf5ae9_post
  tags:
  - Default
